# Generated by Django 3.1.2 on 2022-02-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220122_0651'),
        ('pages', '0002_auto_20220201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
