# Generated by Django 3.1.2 on 2022-02-03 05:06

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_datasource'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='datasource',
            name='codat_id',
            field=models.CharField(default=1, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 5, 6, 16, 627965, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid_time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
