# Generated by Django 3.1.4 on 2022-02-03 07:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220203_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 7, 16, 21, 480805, tzinfo=utc)),
        ),
    ]
