# Generated by Django 3.1.2 on 2022-02-03 06:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_auto_20220203_0506'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasource',
            old_name='url',
            new_name='redirect',
        ),
        migrations.RemoveField(
            model_name='datasource',
            name='created_at',
        ),
        migrations.AddField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 6, 36, 24, 351057, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='datasource',
            name='last_sync',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='datasource',
            name='platform',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datasource',
            name='status',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
