# Generated by Django 3.1.2 on 2022-02-05 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220203_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='title',
            new_name='company',
        ),
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(default='description', max_length=100),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 5, 6, 50, 27, 241373, tzinfo=utc)),
        ),
    ]
