# Generated by Django 3.1.4 on 2022-02-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20220203_0637'),
        ('pages', '0006_auto_20220203_0716'),
    ]

    operations = [
    ]
