# Generated by Django 3.1.4 on 2022-02-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220205_0650'),
        ('pages', '0007_merge_20220203_0734'),
    ]

    operations = [
    ]
