# Generated by Django 3.1.4 on 2022-02-13 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20220205_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 13, 17, 0, 8, 839068, tzinfo=utc)),
        ),
    ]
