# Generated by Django 3.1.4 on 2022-02-10 13:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_merge_20220205_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 10, 13, 16, 8, 720871, tzinfo=utc)),
        ),
    ]
