# Generated by Django 3.1.4 on 2022-02-13 17:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20220213_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
