# Generated by Django 3.1.4 on 2022-01-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220122_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='eni',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='entity_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='zip',
            field=models.CharField(default='', max_length=30),
        ),
    ]
